### ISSUE TITLE
Text of item selected

### ISSUE THREAD

**Issue by Alikaraki95** [abumoallim/Android-Multi-Select-Dialog#1]
Hey,

Thanks alot for the library. I used it and it works fine, however, i have 1 issue, How do i get the text of the item that i selected ? I can get the ID just fine.

Thanks in Advance.

**Comment by abumoallim** [comment]
Library has been enhanced with more features.
Check it here
https://github.com/abumoallim/Android-Multi-Select-Dialog/blob/master/README.md

**Comment by abumoallim** [comment]
Hello ,

I have updated the library with the feature you stated .

Regards,
Abubakker Moallim

**Comment by Alikaraki95** [comment]
Thanks alot :) I already made the changes to the library before you tell me, i thought of making a pull request but then just waited to see if you're fine with it ! Anyway, thanks alot :+1:
