### ISSUE TITLE
Selection on scroll - Bug

### ISSUE THREAD

**Issue by Alikaraki95** [abumoallim/Android-Multi-Select-Dialog#3]
I didn't look into this in code terms, but if you already have a selection, then deselect it and scroll up / down, the item will be selected again.

I'll get back to this when i finish editing my own stuff,

-Ali.

**Comment by abumoallim** [comment]
Will update the code today. Thank you for your interest in this library.

Regards,
Abubakker Moallim

**Comment by Alikaraki95** [comment]
I'll reply back to you tonight after testing and proofreading my code.
