### ISSUE TITLE
Very low Limit of items 

### ISSUE THREAD

**Issue by SyedSumair** [abumoallim/Android-Multi-Select-Dialog#4]
I think there is an issue when the MultiSelectModel object have an 'id' greater than 127, It does not allow user to select that item on checklist.

**Comment by abumoallim** [comment]
Can you please share your code.

**Comment by SyedSumair** [comment]
Getting Data from service and setting MultiSelectModel as :
 brands = new ArrayList<>();
            for (int i = 0; i < data.getBrands().size(); i++) {
                MultiSelectModel model = new MultiSelectModel(i, data.getBrands().get(i).getName());
                brands.add(model);
            }

MultiSelectDialog multiSelectDialog = new MultiSelectDialog()
                            .title("Select Brands") //setting title for dialog
                            .titleSize(15)
                            .positiveText("Done")
                            .negativeText("Cancel")
                            .preSelectIDsList(preSelBrand)
                            .multiSelectList(brands) // the multi select model list with ids and name
                            .onSubmit(new MultiSelectDialog.SubmitCallbackListener() {
                                @Override
                                public void onSelected(ArrayList<Integer> selectedIds, ArrayList<String> selectedNames, String dataString) {
                                    selectedBrands = dataString;
                                    tvSelectBrand.setText("Select Brands(" + selectedIds.size() + " items selected)");
                                    preSelBrand = selectedIds;
                                    Log.d("selected", "BRANDS" + selectedBrands[0]);
                                }

                                @Override
                                public void onCancel() {
                                    preSelBrand = new ArrayList<Integer>();
                                    tvSelectBrand.setText("Select Brands");
                                }


                            });
                    multiSelectDialog.show(getSupportFragmentManager(), "multiSelectDialog");


I can check only item that have an id less than 128

**Comment by abumoallim** [comment]
Please update the library. issue is solved 27e18bbc02bb74193844651bd7ffcd3b180b9cb5

**Comment by SyedSumair** [comment]
Thanks! 👍 :
