### ISSUE TITLE
None of items selected

### ISSUE THREAD

**Issue by gubi95** [abumoallim/Android-Multi-Select-Dialog#6]
It would be nice if you create setting for minimum number of selected items, for example I want to select 1+ items or 0. When I try to deselect all items I got Toast message with text like this: "Please select atleast one option" and I have to do workarounds.

**Comment by abumoallim** [comment]
I am pretty  confused with your example. Can you explain me once more with another example ?

**Comment by gubi95** [comment]
Ok, let's make it simple: your dialog forces to select at least one item. Can you create flag for this? true - force at least one item to be selected, false - all items can be deselected.

**Comment by abumoallim** [comment]
Ok, this is fine. But why you need no items selection option. You can simply cancel the dialog

**Comment by gubi95** [comment]
That's true, but when user treats cancels as just closing dialog then he loses all selected items. Do you see my point?

**Comment by abumoallim** [comment]
ok

**Comment by gubi95** [comment]
Thank you, I will be waiting for updates. Your dialog is pretty cool! :)
