### ISSUE TITLE
set limit for item selection

### ISSUE THREAD

**Issue by hamzashahid91** [abumoallim/Android-Multi-Select-Dialog#7]
First of all thanks for the great work you have done in this repo ...  while using your library there is need to set limit on min and max number of item that can be selected currently minimum is set to 1 by default but I need to set it while creating the dialog. How can i achieve this?

**Comment by abumoallim** [comment]
Will update the library with this option

**Comment by hamzashahid91** [comment]
Can i make a PR for this option as i need it on urgent basis

**Comment by abumoallim** [comment]
Will update as soon as possible.

**Comment by hamzashahid91** [comment]
I have created a pull request for min and max selection limit please review and merge :)

**Comment by abumoallim** [comment]
Yes I am updating that.

Regards,
Abubakker Moallim

**Comment by hamzashahid91** [comment]
Can you please make a new release for the latest PR

**Comment by abumoallim** [comment]
updated!
